name: CI-pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code from the repo
        uses: actions/checkout@v4

      - name: Setup go lang on build runner
        uses: actions/setup-go@v2
        with: 
          go-version: 1.22

      - name: Initialize Go module
        run: |
          go mod init Yogesh-Go-Web-App
          go mod tidy

      - name: Build the code 
        run: go build -o yogesh-web-app .

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code from the repo 
        uses: actions/checkout@v4

      # - name: Run go lang lint 
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: v1.56.2

  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/yogeshwebapp:${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/yogesh-web-app/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "yogeshatigre2000@gmail.com"
        git config --global user.name "Yogesh Atigre"
        git add helm/yogesh-web-app/values.yaml
        git commit -m "Update tag in Helm chart"
        git push
